# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/blk_mem/blk_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem || ORIG_REF_NAME==blk_mem} -quiet] -quiet
